/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FanRouteImport } from './routes/fan'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveStreamIdRouteImport } from './routes/live.$streamId'

const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveStreamIdRoute = LiveStreamIdRouteImport.update({
  id: '/live/$streamId',
  path: '/live/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/fan': typeof FanRoute
  '/live/$streamId': typeof LiveStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/fan': typeof FanRoute
  '/live/$streamId': typeof LiveStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creator': typeof CreatorRoute
  '/explore': typeof ExploreRoute
  '/fan': typeof FanRoute
  '/live/$streamId': typeof LiveStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/creator' | '/explore' | '/fan' | '/live/$streamId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/creator' | '/explore' | '/fan' | '/live/$streamId'
  id: '__root__' | '/' | '/creator' | '/explore' | '/fan' | '/live/$streamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorRoute: typeof CreatorRoute
  ExploreRoute: typeof ExploreRoute
  FanRoute: typeof FanRoute
  LiveStreamIdRoute: typeof LiveStreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$streamId': {
      id: '/live/$streamId'
      path: '/live/$streamId'
      fullPath: '/live/$streamId'
      preLoaderRoute: typeof LiveStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorRoute: CreatorRoute,
  ExploreRoute: ExploreRoute,
  FanRoute: FanRoute,
  LiveStreamIdRoute: LiveStreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
